services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keymaster_php
    depends_on:
      - mysql  
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  php2:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: keymaster_php2
      depends_on:
        - mysql  
      ports:
        - 8081:80
      volumes:
        - .:/var/www/html

  mysql:
    image: mysql:latest
    container_name: keymaster_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: keymaster_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80


volumes:
  mysql_data:



